#!/bin/bash
script_dir="$(dirname "$(which "$0")")"
paskpass="${script_dir:+$script_dir/}paskpass"
keys=$($paskpass "$@")
password=$(echo "$keys" | cut -d',' -f1)
totp=$(echo "$keys" | cut -d',' -f2)

if [ -n "$password" ]; then
    if [ -n "$totp" ]; then
        sshpass -p "$password" -o "$totp" scp "$@"
    else
        sshpass -p "$password" scp "$@"
    fi
else
    scp "$@"
fi